### ISSUE TITLE
Windows resource limits

### ISSUE THREAD

**Issue by Nugine** [Nugine/rlimit#16]
Currently, this crate has no items when targeting windows.

Add support for windows resource limits.

And then change the description.

> <del>A simple wrapper for getrlimit and setrlimit.</del>

> Resource limits

**Comment by Nugine** [comment]
Does windows have any API for resource limits?

**Comment by bee-san** [comment]
There's a Python library for this that looks to work, maybe take a look at their source code?
https://stackoverflow.com/a/28212496

**Comment by Nugine** [comment]
> There's a Python library for this that looks to work, maybe take a look at their source code?
> https://stackoverflow.com/a/28212496

<https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio>

The windows api:
```rust
rlimit::setmaxstdio(new_max)?;
let max = rlimit::getmaxstdio();
```

**Comment by Nugine** [comment]
I can't find a binding for `_setmaxstdio`. I will leave the issue open until I have enough time to find a way.

If someone needs to operate windows resource limits, feel free to open a PR.
