### ISSUE TITLE
cgroup-specific limits

### ISSUE THREAD

**Issue by itamarst** [Nugine/rlimit#20]
Thanks for a handy little library.

I'm currently looking into memory limits, and beyond system RAM and rlimit, on Linux there's also cgroup-specific limits for RAM and CPU. E.g. `/sys/fs/cgroup/memory/memory.limit_in_bytes`.

I might try to submit a PR, if I have time.

**Comment by Nugine** [comment]
Welcome

**Comment by itamarst** [comment]
Turned out cgroups is a lot more complex than I initially realized. Ended up trying https://github.com/kata-containers/cgroups-rs/, which AFAICT is only package that supports both v1 and v2.
