### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by smoelius** [Nugine/rlimit#28]
Could I make a small request? Could you please publish a changelog, especially for breaking changes (e.g., 0.6.2 -> 0.7.0)?

I only ask because I use your crate and benefit from it. 😀

Thanks! 🙏

**Comment by Nugine** [comment]
OK. I will add a changelog soon.

In short, rlimit [0.6.2 → 0.7.0](https://github.com/Nugine/rlimit/compare/v0.6.2...v0.7.0)
+ adds windows support ([rlimit::getmaxstdio](https://docs.rs/rlimit/latest/rlimit/fn.getmaxstdio.html), [rlimit::setmaxstdio](https://docs.rs/rlimit/latest/rlimit/fn.setmaxstdio.html))
+ moves [rlimit::utils::increase_nofile_limit](https://docs.rs/rlimit/0.6.2/rlimit/utils/fn.increase_nofile_limit.html) to [rlimit::increase_nofile_limit](https://docs.rs/rlimit/0.7.0/rlimit/fn.increase_nofile_limit.html)
+ removes `rlimit::utils::get_kern_max_files_per_proc` from public interfaces

**Comment by Nugine** [comment]
Resolved by d45f467a61edc34d3c6323ca18f9850f8c027b43

**Comment by smoelius** [comment]
Awesome. Thanks!
