### ISSUE TITLE
getrlimit64 not defined by musl

### ISSUE THREAD

**Issue by ProkopRandacek** [Nugine/rlimit#58]
Hi :D

I'm getting a build fail on musl system when compiling this crate (as pijul dependency):

```
error: linking with `cc` failed: exit status: 1
  |
...
  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/13.1.1/../../../../x86_64-alpine-linux-musl/bin/ld: /home/prokop/source/pijul/target/debug/deps/pijul-16f393209566f5b5.2tqz6d1q4sfl10k5.rcgu.o: in function `rlimit::unix::getrlimit':
          /home/prokop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rlimit-0.6.2/src/unix.rs:141:(.text._ZN6rlimit4unix9getrlimit17h553ee6606f38f36cE+0xa5): undefined reference to `getrlimit64'
          collect2: error: ld returned 1 exit status
```

I assume this is because unlike glibc [1] [2], musl does not define a 64 version of the `getrlimit` function [3]

[1]: https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/getrlimit.c;h=a6534b1fb880b9a9c18f7fe14df59f2a820e1ead;hb=HEAD
[2]: https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/getrlimit64.c;h=f55238fde3ed6d68ceb277f40c35dc1680af09ca;hb=HEAD
[3]: https://git.musl-libc.org/cgit/musl/tree/src/misc/getrlimit.c

**Comment by Nugine** [comment]
The latest version of `rlimit` is v0.10.1. You can upgrade `pijul`'s dependencies and see whether it still fails.

I think the problem may be solved by upgrading since `rlimit` scans cfg from `libc` source code. Otherwise there may be an issue in `libc`.

**Comment by ProkopRandacek** [comment]
On Wed Aug 23, 2023 at 8:30 AM CEST, Nugine wrote:
> I think the problem may be solved by upgrading since `rlimit` scans
> cfg from `libc` source code. Otherwise there may be an issue in
> `libc`.

oops youre right. Updating pijuls dependencies fixes the issue. I will
open a issue on the pijul repository instead.
